# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech64_10.4/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/shuziluoji/color_game/color_game.cache/wt [current_project]
set_property parent.project_path E:/shuziluoji/color_game/color_game.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/shuziluoji/color_game/color_game.srcs/sources_1/new/Game.v
  E:/shuziluoji/color_game/color_game.srcs/sources_1/new/Top_module.v
  E:/shuziluoji/color_game/color_game.srcs/sources_1/new/Top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/shuziluoji/color_game/color_game.srcs/constrs_1/new/color_game.xdc
set_property used_in_implementation false [get_files E:/shuziluoji/color_game/color_game.srcs/constrs_1/new/color_game.xdc]


synth_design -top Top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
